
server {
   listen localhost;
   client_max_body_size 10;# a voir pour M

    root ./src/www;
    index index.html index.php;

    location /site1 {
      #  root ./src/www/;
       index top_secret.html;
       allowed_methods GET;
    }
}
