server {
    # Erreur : Port hors limite
    # listen 80.80.80.80:70000; 
    
    # Erreur : IP mal formée (trop d'octets)
    # listen 127.0.0.1.1:8080; 

    # Erreur : Caractère interdit dans le nom
    server_name my_server@domain.com;
}