server {
    listen 8080;
    
    # Erreur : Dossier qui n'existe pas
    # root /tmp/dossier/fantome/nulle_part;

    # Erreur : error_page pointant sur un dossier au lieu d'un fichier
    # error_page 404 /var/www/html/;

    # Erreur : Dossier d'upload sans droits d'écriture (teste avec un dossier root)
    upload_path /root; 
}