server {
    listen 8080;

    # Erreur : 301 sans URL de redirection
    # return 301;

    # Erreur : CGI pointant sur un binaire non-exécutable (ex: un .txt)
    # cgi .php /etc/passwd;

    # Erreur : Index avec un "/" qui n'est pas à la fin
    index /main.html index.php;
}