server {
    listen 8080;

    # Erreur : Unité inconnue
    # client_max_body_size -1000000000000000;

    # Erreur : Valeur négative
    # client_max_body_size -50M;

    location / {
        # Erreur : Méthode non supportée
        allowed_methods GET PUT PATCH;
    }
}