# Erreur : Directive allowed_methods en dehors d'un bloc server ou location
allowed_methods GET;

server {
    listen 8080;
    
    # Erreur : Location vide (si tu check le getLocations().empty())
    location /test {
    }
}