
    server {
        listen 8080;
        server_name localhost www.localhost;

        root /var;

        client_max_body_size 10000000;

        error_page 404 ./src/errors/404.html;
       error_page 500 502 503 504 ./src/errors/50x.html;

        # -------- LOCATION ROOT --------
        location / {
          
        }

        # -------- LOCATION UPLOAD --------
        location /upload {
            
        }

        # -------- LOCATION CGI --------
        location /cgi-bin {
           
        }
    }

    server {
        listen 127.0.0.1:6780;
        server_name test.local;

        root ./src/www;
        

        # redirection
        location /old {

        }

        # directory listing off
        location /private {

        }
    }

