server {
    listen 127.0.0.1:8000;
    server_name webserv.com;
    
    root ./src/www;
    error_page 404 ./src/errors/404.html;

    # 1. / doit répondre UNIQUEMENT à GET
    location / {
        allowed_methods GET;
        autoindex on;
    }

    # 2. Extension .bla doit répondre à POST (appel au CGI)
    location .bla {
        allowed_meth POST;
        cgi .bla ./cgi_test;
    }

    # 3. /post_body doit répondre à POST avec maxBody 100
    location /post_body {
        allowed_methods POST;
        client_max_body_size 100;
    }

    # 4. /directory/ doit répondre à GET, root YoupiBanane, index youpi.bad_extension
    location /directory/ {
        allowed_methods GET;
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
    }

    # Tes routes bonus / utilitaires
    location /upload {
        allowed_upload on;
        allowed_methods GET POST DELETE; # On laisse POST/DELETE pour que l'upload serve à quelque chose
        upload_path ./src/www/upload;
        autoindex on;
    }

    location /cgi-bin {
        allowed_methods GET POST;
        cgi .php /usr/bin/php-cgi;
        cgi .py /usr/bin/python3;
    }
}

server {
    listen 127.0.0.1:6767;
    server_name second_server;
    root ./src/www/site2;
    index index.html;
}