
 # Configuration globale (optionnel selon ton sujet)
# max_clients 100;

server {

    listen 127.0.0.1:8080;
    # listen 0.0.0.0:6767;
    # server_name webserv.com;
    # client_max_body_size 10000000000000000000000000000000;# a voir pour M

    # error_page 404  ./src/errors/404.html;
    # error_page 500 502 503 504 600 ./src/errors/500.html;# a voir pour le x ex: 50x
    # root ./src/www; je peux le definir qu'une fois 
    index index.html index.php;



    location / {
        allowed_methods GET POST;
        autoindex on;
        # error_page 404  ./src/errors/404.html;
    }

    location /old-page {
        return 301 http://localhost:8080/new-page;
    }

    location /upload {
        allowed_upload on;
        allowed_methods GET POST DELETE;
        upload_path ./src/www;
        autoindex on;
    }

    location /cgi-bin {
        allowed_methods GET POST;
        cgi .php /usr/bin/php-cgi;
        cgi .py /usr/bin/python3;
    }

    location /site1 {
        # allowed_methods GET;
        root ./src/www/;
        index index.html;
    }
}

server {
    listen 127.0.0.1:6767;
    server_name second_server;

    root ./src/www/site2;
    index index.html;
}
