server {
    listen 8080;
    server_name localhost;
    root /home/juduchar/Common/Webserv/src/www;
    client_max_body_size 1000;
    index index.html;
    autoindex on;
    cgi_handler .bla /home/juduchar/Common/Webserv/cgi_tester;

    location / {
        allowed_methods GET POST;
    }

    location .bla {
        allowed_methods GET POST;
    }

    location /post_body {
        allowed_methods POST;
        client_max_body_size 100;
    }

    location /directory/ {
        allowed_methods GET;
        root /home/juduchar/Common/Webserv/src/www/YoupiBanane;
        index youpi.bad_extension;
    }
}