server { #qwderthtgrewqwegrthqwfcwq
	listen 80:80 1245:34 8765 567 54;
	root /dev ;
	server_name site1;
	client_max_body_size 345678765;

	location /image {
		root /tmp;
		client_max_body_size 1;
	}
}
