
server {
   listen 127.0.0.1:8080;
   client_max_body_size 10;# a voir pour M

    root ./src/www;
    index index.html index.php;

    location /secret {
       root ./src/www/site1;
       index top_secret.html;
    }
}
