server {
    # Port et Host
    listen 127.0.0.1:8080;
    
    # Noms du serveur (séparés par des espaces)
    server_name localhost webserv.com;
    
    # Taille max du corps de la requête (en octets, donc 10M = 10485760)
    client_max_body_size 10000;

    

    # Pages d'erreur
    error_page 404 ./src/errors/404.html;
    error_page 500 ./src/errors/500.html;
    error_page 502 ./src/errors/500.html;
    error_page 503 ./src/errors/500.html;
    error_page 504 ./src/errors/500.html;

    # Configuration globale
    root ./src/www;
    # index index.html index.php;

        
    autoindex on;
    # Routes
    location / {
        allowed_methods GET POST;
        autoindex on;
    }

    location /old-page {
        allowed_methods GET POST;
        upload_path ./src/www/uploads;
        allowed_upload on;
        return 301 http://127.0.0.2:8080;
    }

    location /uploads {
        allowed_methods GET POST DELETE;
        allowed_upload on;
        upload_path ./src/www/uploads;
        # root ./src/www;
        autoindex on;
    }

    location /cgi-bin {
        allowed_methods GET POST;
        #root ./src/www;
        cgi_handler .php /usr/bin/php-cgi;
        cgi_handler .py /usr/bin/python3;
    }

    location /secret {
        allowed_methods GET;
        root ./src/www/site1;
        # index top_secret.html;
        autoindex on;
    }
}

# Deuxième serveur sur le même port (différencié par server_name)
server {
    listen 127.0.0.2:8080;
    server_name second_server.fr;

    root ./src/www/site2;
    index home.html;
    
    location / {
        allowed_methods GET;
        autoindex off;
    }
}