server {
    # Port simple
    listen 8080;
    
    # Nom du serveur
    server_name localhost;
    
    # Le dossier racine magique (existe partout, 0 erreur garantie)
    root /home/julien/Webserv/src/www;
    
    # Configuration de base
    client_max_body_size 1000000;
    index index.php index.html;
    autoindex on;

    cgi_handler .php /usr/bin/php-cgi;
    
    # Une seule route de base
    location / {
        allowed_methods GET POST;
    }
}