


server 
{ 
	listen	8080;  			
	root	/data;

	location /ima"{"ge { 
		autoindex 
		on;
		root /www;
		#wfweqcawcwcew
	} 
	location /sqwsdfg { 

	}
	

}

#dfvwafecvfwqcqesqw

server { #qwderthtgrewqwegrthqwfcwq
		location /sqwsdfg { 

		}
	}